services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${WS_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${WS_PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin:
    driver: local